#version should be only changed with RELEASE eminent, see RELEASE.md

version: 2.8.0-ci-{build}
image:
  - Visual Studio 2019
  - ubuntu1804

clone_depth: 1
pull_requests:
  do_not_increment_build_number: false

init:
  - ps: |
      git config --global core.autocrlf input
      $env:CAN_PUBLISH = $true
      if ($env:APPVEYOR_REPO_TAG -eq "true") {
        $ver = $env:APPVEYOR_REPO_TAG_NAME
        if($ver.StartsWith("v") -eq $true) { $ver = $ver.Substring(1) }
        try
        {         
          Update-AppveyorBuild -Version $ver        
        }
        catch
        {
          Write-Output "Update-AppveyorBuild Fail to change version to TAG: '$env:APPVEYOR_REPO_TAG_NAME'"   -ForegroundColor Red
          Write-Output "Exception Error: $PSItem.Exception.Message" -ForegroundColor Red
          $env:CAN_PUBLISH = $false
        }
      }

  - ps: |
      if( $ver -match '^\d+\.\d+\.\d+$') {
        $env:IS_RELEASE = $true 
      } else  {
           $env:IS_RELEASE = $false }

  - ps: |
      Write-Host "APPVEYOR_BUILD_VERSION='$env:APPVEYOR_BUILD_VERSION'" -ForegroundColor Yellow
      Write-Host "APPVEYOR_REPO_TAG_NAME= '$env:APPVEYOR_REPO_TAG_NAME'" -ForegroundColor Yellow

skip_commits:
  files:
    - docs/*
    - art/*
    - '**/*.md'    
    - .gitignore
    - .editorconfig
  message: /updated readme.*|update readme.*s|update docs.*|update version.*|update changelog.*/

environment:
  matrix:
    - BUILD_TARGET: base
    - BUILD_TARGET: fsharp

build_script:
- cmd: dotnet build src/CommandLine/ -c Release --version-suffix %APPVEYOR_BUILD_VERSION% /p:BuildTarget=%BUILD_TARGET%
- sh: dotnet build src/CommandLine/ -c Release --version-suffix $APPVEYOR_BUILD_VERSION /p:BuildTarget=$BUILD_TARGET

test_script: 
- cmd: dotnet test tests/CommandLine.Tests/ /p:BuildTarget=%BUILD_TARGET%
- sh: dotnet test tests/CommandLine.Tests/ /p:BuildTarget=$BUILD_TARGET  -f netcoreapp2.0

after_test:
- cmd: dotnet pack src/CommandLine/ -c Release --version-suffix %APPVEYOR_BUILD_VERSION% /p:BuildTarget=%BUILD_TARGET%
- sh: dotnet pack src/CommandLine/ -c Release --version-suffix $APPVEYOR_BUILD_VERSION /p:BuildTarget=$BUILD_TARGET

artifacts:
- path: 'src/CommandLine/bin/Release/*.nupkg'
  name: NuGetPackages
- path: 'src/CommandLine/bin/Release/*.snupkg'
  name: symbol  
on_failure:
- cmd: |
    tree /f /a >files.lst
    appveyor PushArtifact .\files.lst -DeploymentName "Failed Build File Listing"

for:
-
  matrix:
    only:
      - image: Visual Studio 2019
  deploy:
  - provider: GitHub
    auth_token:
      secure: hVyVwHl0JiVq0VxXB4VMRWbUtrGclIzadfnWFcWCQBLvbgMLahLBnWlwGglT63pZ
    artifact: /.*(\.|\.s)nupkg/
    prerelease: false
    force_update: true #fsharp package runs as separate build job, so have to force_update to add fsharp.nuget added
    on:
      APPVEYOR_REPO_TAG: true
      CAN_PUBLISH: true

  - provider: NuGet
    api_key:
      secure: Ab4T/48EyIJhVrqkfKdUxmHUtseEVuXuyrGACxZ0KN35rb/BzABlBM2YjZojicvT
    artifact: 'NuGetPackages'
    on:
      APPVEYOR_REPO_TAG: true
      CAN_PUBLISH: true
      IS_RELEASE : true

